// <auto-generated />
namespace DataAccessLayer1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migone));
        
        string IMigrationMetadata.Id
        {
            get { return "202403050422392_migone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
